### PR TITLE
Fix null location in VariableAnnotator#shallowAnnotateArray().

### PR DESCRIPTION
**Pull request by CharlesZ-Chen**
A fix to commit: https://github.com/typetools/checker-framework-inference/commit/923e3455816a9e434e385a0c6522294ef6da198d .

Original code in above commit might pass null `location` into method `createEquivalentSlotConstraints()`, which will cause a `VariableAnnotation` with null `location` generated. Also, this code will cause NullPointerException in the `opprop` version (when using updated `slotManager` to create `VariableAnnotation`.).

This PR change it from `null` to `MISSING_LOCATION`.

### CODE REVIEW

**Comment by CharlesZ-Chen** [comment]
The travis failure seems as same as the one in current master branch and not related to this PR. #55 should fix this failure.

**Comment by wmdietl** [comment]
@CharlesZ-Chen can you sync and see whether the travis failure goes away?

**Comment by wmdietl** [comment]
#55 is merged, but master unfortunately still fails.
In #45 I'm getting a bit further, but for some strange reason a git usage fails.
Do you have an idea what is going wrong? Feel free to push to #45 to test.

**Comment by wmdietl** [comment]
The latest version of #45 fixed the issues and I merged it. Pulling in master should fix this PR.

**Comment by CharlesZ-Chen** [comment]
Hi Prof. Dietl,

Sorry for the late response. I've synced this PR with master.

Best,

**Comment by wmdietl** [comment]
Thanks for the fix!

**Pull request merged**
